= conservation de la hiérarchie des dossiers
:allow-uri-read: 




=== conservation de la hiérarchie des dossiers

Par défaut, la reprise après sinistre conserve la hiérarchie d'inventaire des machines virtuelles (structure des dossiers) lors d'un basculement.  Si le dossier requis n'est pas présent sur la cible de récupération, la fonction de récupération après sinistre le crée.

Vous pouvez désormais modifier ce paramètre en désignant un nouveau dossier parent pour la machine virtuelle ou en décochant l'option **Conserver la hiérarchie de dossiers d'origine**.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.adoc["Créer un plan de réplication"].



=== Mise à jour simplifiée de l'agent de console

La reprise après sinistre prend désormais en charge un processus simplifié pour l'utilisation de plusieurs agents Console dans un environnement de travail.  Pour changer d'agent de console, vous devez modifier la configuration de votre vCenter, redécouvrir les informations d'identification et actualiser les plans de réplication pour utiliser le nouvel agent de console.

Pour plus d'informations, voir link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agents.html["Agents de la console de commutation"].
