---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 'Introduction à NetApp Disaster Recovery à l"aide d"Amazon EVS et Amazon FSx for NetApp ONTAP.  Bien que le connecteur puisse être installé dans n"importe lequel de vos emplacements réseau, pour NetApp Disaster Recovery, nous vous recommandons d"installer le connecteur sur le site DR.  Cela garantit qu"en cas de défaillance du site principal, l"interface utilisateur de la console NetApp continue d"être en contact avec l"agent de la console et peut orchestrer le processus de récupération au sein de ce site DR.' 
---
= Installer l'agent NetApp Console pour NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Un agent de NetApp Console est un logiciel NetApp exécuté dans votre cloud ou sur votre réseau local.  Il exécute les actions que la NetApp Console doit effectuer pour gérer votre infrastructure de données.  L'agent de console interroge en permanence le logiciel NetApp Disaster Recovery en tant que couche de service pour connaître les actions qu'il doit entreprendre.

Pour NetApp Disaster Recovery, les actions exécutées orchestrent les clusters VMware vCenter et les instances de stockage ONTAP à l'aide d'API natives pour chaque service respectif afin de fournir une protection aux machines virtuelles de production exécutées dans un emplacement sur site.  Bien que l'agent de console puisse être installé dans n'importe lequel de vos emplacements réseau, pour NetApp Disaster Recovery, nous vous recommandons d'installer l'agent de console sur le site DR.  Cela garantit qu'en cas de défaillance du site principal, l'interface utilisateur de la console basée sur le cloud NetApp continue d'être en contact avec l'agent de la console et peut orchestrer le processus de récupération au sein de ce site DR.

Pour utiliser le service, installez l’agent Console en mode standard. Pour en savoir plus sur les types d'installations de l'agent Console, consultez https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["En savoir plus sur les modes de déploiement de la NetApp Console | Documentation NetApp"^] .

Bien que l’agent de console soit essentiel à l’utilisation du service, les étapes d’installation de l’agent de console dépendent de vos besoins et de la configuration du réseau.  Il n’entre pas dans le cadre de ces informations de fournir des instructions spécifiques pour l’installation.

La méthode la plus simple pour installer l’agent de console avec Amazon AWS consiste à utiliser AWS Marketplace. Pour plus d'informations sur l'installation de l'agent Console à l'aide d'AWS Marketplace, consultez https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Créer un agent de console depuis AWS Marketplace | Documentation NetApp"^] .
