---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: 'Introduction à NetApp Disaster Recovery à l"aide d"Amazon EVS et Amazon FSx for NetApp ONTAP.' 
---
= Découvrez la reprise après sinistre NetApp avec Amazon Elastic VMware Service et Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery aide à protéger les charges de travail VMware en répliquant les données des environnements sur site vers Amazon EVS et Amazon FSx for NetApp ONTAP pour la reprise après sinistre.

L’un des principaux défis de toute solution DR est la gestion du coût supplémentaire lié à l’achat, à la configuration et à la maintenance de ressources de calcul, de réseau et de stockage supplémentaires, simplement pour fournir une infrastructure de réplication et de récupération DR.  Une option populaire pour protéger les ressources virtuelles critiques sur site consiste à utiliser des ressources virtuelles hébergées dans le cloud comme infrastructure de réplication et de récupération DR.  Amazon est un exemple d’une telle solution qui peut fournir des ressources rentables compatibles avec les infrastructures de machines virtuelles hébergées par NetApp ONTAP .

Amazon a lancé Amazon Elastic VMware Service (Amazon EVS), qui permet d'intégrer VMware Cloud Foundation à votre cloud privé virtuel (VPC). Amazon EVS offre la résilience et les performances d'AWS, ainsi que les logiciels et outils VMware que vous connaissez, ce qui permet à Amazon EVS vCenters de s'intégrer à votre infrastructure virtualisée sur site.

Bien qu'Amazon EVS intègre des ressources de stockage, l'utilisation du stockage natif peut en limiter l'efficacité pour les organisations dont les charges de travail sont gourmandes en stockage. Dans ces cas, l'association d'Amazon EVS avec Amazon FSx for NetApp ONTAP storage (Amazon FSxN) peut offrir une solution de stockage plus flexible. De plus, lorsque vous utilisez des solutions de stockage NetApp ONTAP sur site pour héberger votre infrastructure VMware, l'utilisation d'Amazon EVS avec FSx for ONTAP offre des fonctionnalités d'interopérabilité et de protection des données entre les environnements sur site et cloud.

Pour plus d'informations sur Amazon FSx for NetApp ONTAP, consultez https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Premiers pas avec Amazon FSx for NetApp ONTAP"^] .
