---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter,amazon elastic vmware service 
summary: 'Introduction à NetApp Disaster Recovery à l"aide d"Amazon EVS et Amazon FSx for NetApp ONTAP.  NetApp Disaster Recovery est une offre de produit sous licence qui doit être achetée avant de pouvoir être utilisée.  Il existe plusieurs types de licences et plusieurs façons d’acheter des licences.' 
---
= Ajoutez le service NetApp Disaster Recovery à votre compte NetApp Console pour Amazon EVS
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery est une offre de produit sous licence qui doit être achetée avant de pouvoir être utilisée.  Il existe plusieurs types de licences et plusieurs façons d’acheter des licences.  Une licence vous donne le droit de protéger une quantité spécifique de données pendant une durée déterminée.

Pour plus d'informations sur les licences NetApp Disaster Recovery , consultezlink:../get-started/dr-licensing.html["Configurer les licences pour NetApp Disaster Recovery"] .



== Types de licences

Il existe deux principaux types de licences :

* NetApp propose unelink:../get-started/dr-licensing.html["Licence d'essai de 30 jours"] que vous pouvez utiliser pour évaluer NetApp Disaster Recovery à l'aide de vos ressources ONTAP et VMware.  Cette licence offre 30 jours d'utilisation pour une quantité illimitée de capacité protégée.
* Achetez une licence de production si vous souhaitez une protection DR au-delà de la période d’essai de 30 jours.  Cette licence peut être achetée via les places de marché de n'importe quel partenaire cloud de NetApp, mais pour ce guide, nous vous recommandons d'acheter votre licence de place de marché pour NetApp Disaster Recovery à l'aide d'Amazon AWS Marketplace.  Pour en savoir plus sur l'achat d'une licence via Amazon Marketplace, consultezlink:../get-started/dr-licensing.html["Abonnez-vous via AWS Marketplace"] .




== Évaluez vos besoins en capacité de reprise après sinistre

Avant d’acheter votre licence, vous devez comprendre la capacité de stockage ONTAP que vous devez protéger.  L’un des avantages de l’utilisation du stockage NetApp ONTAP est la grande efficacité avec laquelle NetApp stocke vos données.  Toutes les données stockées dans un volume ONTAP (comme les machines virtuelles hébergeant une banque de données VMware) sont stockées de manière très efficace.  ONTAP utilise par défaut trois types d'efficacité de stockage lors de l'écriture de données sur un stockage physique : compactage, déduplication et compression.  Le résultat net est une efficacité de stockage comprise entre 1,5:1 et 4:1 selon les types de données stockées.  En fait, NetApp propose une https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["garantie d'efficacité de stockage"^] pour certaines charges de travail.

Cela peut vous être bénéfique car NetApp Disaster Recovery calcule la capacité à des fins de licence une fois que toutes les efficacités de stockage ONTAP ont été appliquées.  Par exemple, supposons que vous ayez provisionné une banque de données NFS de 100 téraoctets (Tio) dans vCenter pour héberger 100 machines virtuelles que vous souhaitez protéger à l'aide du service.  De plus, supposons que lorsque les données sont écrites sur le volume ONTAP , les techniques d'efficacité de stockage appliquées automatiquement entraînent une consommation de seulement 33 Tio par ces machines virtuelles (efficacité de stockage 3:1).  NetApp Disaster Recovery doit être concédé sous licence uniquement pour 33 Tio, et non pour 100 Tio.  Cela peut représenter un avantage considérable sur le coût total de possession de votre solution DR par rapport à d’autres solutions DR.

.Étapes
. Pour déterminer la quantité de données consommée sur chaque volume hébergeant une banque de données VMware à protéger, déterminez la consommation de capacité sur disque en exécutant la commande ONTAP CLI pour chaque volume : `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` .
+
Par exemple:

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. Notez la valeur *Total physique utilisé* pour chaque volume.  Il s’agit de la quantité de données que NetApp Disaster Recovery doit protéger et c’est la valeur que vous utiliserez pour déterminer la capacité dont vous avez besoin pour obtenir une licence.

