---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 'L"agent NetApp Console orchestre la connexion et la gestion entre la NetApp Console et les ressources de stockage cloud ou sur site.' 
---
= Installer l'agent NetApp Console pour NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Un agent NetApp Console vous permet de connecter vos déploiements NetApp Console à votre infrastructure afin d'orchestrer en toute sécurité des solutions sur AWS, Azure, Google Cloud ou dans des environnements sur site. L'agent Console exécute les actions que la NetApp Console doit effectuer pour gérer votre infrastructure de données. L'agent Console interroge en permanence la couche de logiciel en tant que service NetApp Disaster Recovery pour toute action qu'il doit entreprendre.

Pour la reprise après sinistre, ces actions orchestrent les clusters VMware vCenter et les instances de stockage ONTAP en utilisant les API natives de chaque service afin de protéger les machines virtuelles de production exécutées sur site. Bien que l’agent Console puisse être installé dans n’importe lequel de vos emplacements réseau, nous recommandons d’installer l’agent Console sur le site de reprise après sinistre pour la reprise après sinistre. L’installation sur le site de reprise après sinistre garantit qu’en cas de défaillance du site principal, l’interface utilisateur de la console NetApp maintient sa connexion à l’agent Console et peut orchestrer le processus de reprise sur ce site de reprise après sinistre.



[[installation]]
== Installation

* Pour utiliser la récupération après sinistre, installez l'agent Console en mode standard. Pour en savoir plus sur les types d'installation de l'agent Console, visitez https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Découvrez les modes de déploiement de la NetApp Console"^].


Les étapes d'installation spécifiques de l'agent Console dépendent de votre type de déploiement. Voir link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["En savoir plus sur les agents de console"^] pour plus d'informations.


TIP: La méthode la plus simple pour installer l'agent Console avec Amazon AWS consiste à utiliser AWS Marketplace. Pour plus d'informations sur l'installation de l'agent Console à l'aide de AWS Marketplace, voir  https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Créez un agent Console à partir de l'AWS Marketplace"^].
