---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: 'L’examen des rapports de reprise après sinistre peut vous aider à analyser votre état de préparation à la reprise après sinistre.  Les rapports prédéfinis incluent un résumé des basculements et des restaurations, les détails de la réplication sur tous les sites et les détails des tâches pour l"année écoulée.' 
---
= Créer des rapports de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
L’examen des rapports de NetApp Disaster Recovery peut vous aider à analyser votre préparation à la reprise après sinistre.  Les rapports prédéfinis incluent un résumé des basculements de test, des détails du plan de réplication et des détails des tâches sur tous les sites d'un compte au cours des sept derniers jours.

Vous pouvez télécharger des rapports au format PDF, HTML ou JSON.

Le lien de téléchargement est valable six heures.

.Étapes
. Connectez-vous à la https://console.netapp.com/["NetApp Console"^] .
. Dans la navigation de gauche de la NetApp Console , sélectionnez *Protection* > *Reprise après sinistre*.
. Dans la barre de navigation de gauche de la NetApp Console , sélectionnez *Plans de réplication*.
. Sélectionnez *Créer un rapport*.
. Sélectionnez le type de format de fichier et la période au cours des 7 derniers jours.
. Sélectionnez *Créer*.
+

NOTE: L’affichage du rapport peut prendre quelques minutes.

. Pour télécharger un rapport, sélectionnez *Télécharger le rapport* et sélectionnez-le dans le dossier Téléchargement de l'administrateur.

